BASEPATH_ := $(dir $(realpath $(word $(words $(MAKEFILE_LIST)),$(MAKEFILE_LIST))))
#BASEPATH_ := $(dir $(word $(words $(MAKEFILE_LIST)),$(MAKEFILE_LIST)))

BASH ?= bash
CC ?= gcc
CXX ?= g++
SCAN_BUILD ?= scan-build
PYTHON2 ?= python2
CPPCHECK ?= cppcheck

SYSTEM = $(shell uname)

SYSTEM_LDFLAGS =

DEBUG ?= no
PROFIL ?= no
WERROR ?= no

ifeq '$(PROFIL)' 'yes'
  DEBUG = yes
endif

ifeq '$(DEBUG)' 'yes'
  CFLAGS = -g
  CPPFLAGS = -g
else
  # force to use optimizations
  CFLAGS += -O3
  CPPFLAGS += -O3
endif
ifeq '$(PROFIL)' 'yes'
  CFLAGS += -pg -no-pie
  CPPFLAGS += -pg -no-pie
endif
CFLAGS += -Wall -pedantic --std=gnu99
CFLAGS += -Wno-missing-braces
CPPFLAGS += -Wall -pedantic

ifeq '$(WERROR)' 'yes'
  CFLAGS += -Werror
endif

LDFLAGS += -pthread
LDFLAGS += $(SYSTEM_LDFLAGS)

ifneq '$(IBM_CPLEX_ROOT)' ''
  ifeq '$(wildcard $(IBM_CPLEX_ROOT)/cplex/include/ilcplex/cplex.h)' ''
    $(error IBM_CPLEX_ROOT defined, but could not find cplex header files)
  endif
  ifeq '$(wildcard $(IBM_CPLEX_ROOT)/cpoptimizer/include/ilcp/cp.h)' ''
    $(error IBM_CPLEX_ROOT defined, but could not find cpoptimizer header files)
  endif
  ifeq '$(wildcard $(IBM_CPLEX_ROOT)/concert/include/ilconcert/iloalg.h)' ''
    $(error IBM_CPLEX_ROOT defined, but could not find concert header files)
  endif
  ifeq '$(wildcard $(IBM_CPLEX_ROOT)/cplex/lib/x86-64_linux/static_pic/libcplex.a)' ''
    $(error IBM_CPLEX_ROOT defined, but could not find cplex library)
  endif
  ifeq '$(wildcard $(IBM_CPLEX_ROOT)/cpoptimizer/lib/x86-64_linux/static_pic/libcp.a)' ''
    $(error IBM_CPLEX_ROOT defined, but could not find cpoptimizer library)
  endif
  ifeq '$(wildcard $(IBM_CPLEX_ROOT)/concert/lib/x86-64_linux/static_pic/libconcert.a)' ''
    $(error IBM_CPLEX_ROOT defined, but could not find concert library)
  endif
  CPLEX_CFLAGS := -I$(IBM_CPLEX_ROOT)/cplex/include
  CPLEX_LDFLAGS := -L$(IBM_CPLEX_ROOT)/cplex/lib/x86-64_linux/static_pic -lcplex -ldl
  CPOPTIMIZER_CPPFLAGS = -I$(IBM_CPLEX_ROOT)/cpoptimizer/include -I$(IBM_CPLEX_ROOT)/concert/include/ -I$(IBM_CPLEX_ROOT)/cplex/include
  CPOPTIMIZER_LDFLAGS = -L$(IBM_CPLEX_ROOT)/cpoptimizer/lib/x86-64_linux/static_pic/ -lcp -L$(IBM_CPLEX_ROOT)/concert/lib/x86-64_linux/static_pic/ -lconcert -lstdc++
endif

OPTS_CFLAGS ?=
OPTS_LDFLGS ?=
USE_LOCAL_OPTS ?= $(shell if test -f $(BASEPATH_)/third-party/opts/libopts.a; then echo "yes"; else echo "no"; fi;)
ifeq '$(USE_LOCAL_OPTS)' 'yes'
  OPTS_CFLAGS := -I$(BASEPATH_)/third-party/opts
  OPTS_LDFLAGS := -L$(BASEPATH_)/third-party/opts -lopts
endif

BORUVKA_CFLAGS ?=
BORUVKA_LDFLAGS ?=
USE_LOCAL_BORUVKA ?= $(shell if test -f $(BASEPATH_)/third-party/boruvka/libboruvka.a; then echo "yes"; else echo "no"; fi;)
ifeq '$(USE_LOCAL_BORUVKA)' 'yes'
  BORUVKA_CFLAGS := -I$(BASEPATH_)/third-party/boruvka
  BORUVKA_LDFLAGS := -L$(BASEPATH_)/third-party/boruvka -lboruvka
endif

ifeq '$(BOR_CPLEX_CFLAGS)' ''
  ifneq '$(CPLEX_CFLAGS)' ''
    BOR_CPLEX_CFLAGS := $(CPLEX_CFLAGS)
  endif
endif

ifeq '$(BOR_GUROBI_CFLAGS)' ''
  ifneq '$(GUROBI_CFLAGS)' ''
    BOR_GUROBI_CFLAGS := $(GUROBI_CFLAGS)
  endif
endif

USE_LOCAL_LPSOLVE ?= $(shell if test -f $(BASEPATH_)/third-party/lpsolve/liblpsolve.a; then echo "yes"; else echo "no"; fi;)
ifeq '$(USE_LOCAL_LPSOLVE)' 'yes'
  LPSOLVE_CFLAGS := -I$(BASEPATH_)/third-party
  LPSOLVE_LDFLAGS := -L$(BASEPATH_)/third-party/lpsolve -llpsolve -ldl
endif

ifeq '$(BOR_LPSOLVE_CFLAGS)' ''
  ifneq '$(LPSOLVE_CFLAGS)' ''
    BOR_LPSOLVE_CFLAGS := $(LPSOLVE_CFLAGS)
  endif
endif


BOR_CC := $(CC)

_BOR_MAKE_VARS := $(filter BOR_%, $(.VARIABLES))
_BOR_MAKE_DEF := $(foreach V,$(_BOR_MAKE_VARS),$(V:BOR_%=%)="$($(V))") DEBUG=no


BLISS_VERSION = 0.73
BLISS_CFLAGS ?=
BLISS_LDFLAGS ?=
USE_BLISS = auto
USE_LOCAL_BLISS ?= $(shell if test -f $(BASEPATH_)/third-party/bliss/libbliss.a; then echo "yes"; else echo "no"; fi;)
ifeq '$(USE_LOCAL_BLISS)' 'yes'
  BLISS_CFLAGS := -I$(BASEPATH_)/third-party
  BLISS_LDFLAGS := -L$(BASEPATH_)/third-party/bliss -lbliss -lstdc++
  USE_BLISS := yes
endif


CLIQUER_CFLAGS ?=
CLIQUER_LDFLAGS ?=
USE_CLIQUER = auto
ifeq '$(USE_CLIQUER)' 'auto'
  USE_CLIQUER_SYSTEM_HEADER ?= $(shell if test -f /usr/include/cliquer/cliquer.h; then echo "yes"; else echo "no"; fi;)
  USE_CLIQUER_SYSTEM_LIB ?= $(shell if test -f /usr/lib/libcliquer.so; then echo "yes"; else echo "no"; fi;)
  ifeq '$(USE_CLIQUER_SYSTEM_HEADER)$(USE_CLIQUER_SYSTEM_LIB)' 'yesyes'
    CLIQUER_CFLAGS := -I/usr/include
    CLIQUER_LDFLAGS := -L/usr/lib -lcliquer
    USE_CLIQUER := yes
  endif
endif

CUDD_CFLAGS ?=
CUDD_LDFLAGS ?=
USE_CUDD ?= auto
ifeq '$(USE_CUDD)' 'auto'
  USE_LOCAL_CUDD ?= $(shell if test -f $(BASEPATH_)/third-party/cudd/libcudd.a; then echo "yes"; else echo "no"; fi;)
  ifeq '$(USE_LOCAL_CUDD)' 'yes'
    CUDD_CFLAGS := -I$(BASEPATH_)/third-party/cudd
    CUDD_LDFLAGS := -L$(BASEPATH_)/third-party/cudd -lcudd
  endif
  ifneq '$(CUDD_CFLAGS)$(CUDD_LDFLAGS)' ''
    USE_CUDD := yes
  endif
endif

SQLITE_CFLAGS ?=
SQLITE_LDFLAGS ?=
USE_SQLITE ?= auto
ifeq '$(USE_SQLITE)' 'auto'
  USE_LOCAL_SQLITE ?= $(shell if test -f $(BASEPATH_)/third-party/sqlite/libsqlite.a; then echo "yes"; else echo "no"; fi;)
  ifeq '$(USE_LOCAL_SQLITE)' 'yes'
    SQLITE_CFLAGS := -I$(BASEPATH_)/third-party/sqlite
    SQLITE_LDFLAGS := -L$(BASEPATH_)/third-party/sqlite -lsqlite -ldl
  endif
  ifneq '$(SQLITE_CFLAGS)$(SQLITE_LDFLAGS)' ''
    USE_SQLITE := yes
  endif
endif
SQLITE_BUILD_CFLAGS ?= -O2 \
    -DSQLITE_OMIT_AUTOINCREMENT \
    -DSQLITE_OMIT_CAST \
    -DSQLITE_OMIT_COMPOUND_SELECT \
    -DSQLITE_OMIT_EXPLAIN \
    -DSQLITE_OMIT_FOREIGN_KEY \
    -DSQLITE_OMIT_TEMPDB \
    -DSQLITE_OMIT_DEPRECATED


LP_LDFLAGS := $(CPLEX_LDFLAGS) $(GUROBI_LDFLAGS) $(LPSOLVE_LDFLAGS)

.DEFAULT_GOAL := all

help:
	@echo "Targets:"
	@echo "    all            - Build library"
	@echo "    doc            - Build documentation"
	@echo "    check          - Build & Run automated tests"
	@echo "    check-valgrind - Build & Run automated tests in valgrind(1)"
	@echo "    check-segfault - Build & Run automated tests in valgrind(1) set up to detect only segfaults"
	@echo "    clean          - Remove all generated files"
	@echo "    analyze        - Perform static analysis using Clang Static Analyzer"
	@echo "    submodule      - Fetch all submodules using git."
	@echo "    third-party    - Build all third-party projects."
	@echo "    third-party-clean - Clean all third-party projects."
	@echo ""
	@echo "Options:"
	@echo "    CC         - Path to C compiler          (=$(CC))"
	@echo "    CXX        - Path to C++ compiler        (=$(CXX))"
	@echo "    SCAN_BUILD - Path to scan-build          (=$(SCAN_BUILD))"
	@echo "    PYTHON2    - Path to python v2 interpret (=$(PYTHON2))"
	@echo ""
	@echo "    DEBUG      'yes'/'no' - Turn on/off debugging   (=$(DEBUG))"
	@echo "    PROFIL     'yes'/'no' - Compiles profiling info (=$(PROFIL))"
	@echo ""
	@echo "Variables:"
	@echo "  Note that most of can be preset or changed by user"
	@echo "    SYSTEM            = $(SYSTEM)"
	@echo "    CFLAGS            = $(CFLAGS)"
	@echo "    LDFLAGS           = $(LDFLAGS)"
	@echo "    USE_LOCAL_OPTS    = $(USE_LOCAL_OPTS)"
	@echo "    OPTS_CFLAGS       = $(OPTS_CFLAGS)"
	@echo "    OPTS_LDFLAGS      = $(OPTS_LDFLAGS)"
	@echo "    USE_LOCAL_BORUVKA = $(USE_LOCAL_BORUVKA)"
	@echo "    BORUVKA_CFLAGS    = $(BORUVKA_CFLAGS)"
	@echo "    BORUVKA_LDFLAGS   = $(BORUVKA_LDFLAGS)"
	@echo "    USE_BLISS         = $(USE_BLISS)"
	@echo "    BLISS_CFLAGS      = $(BLISS_CFLAGS)"
	@echo "    BLISS_LDFLAGS     = $(BLISS_LDFLAGS)"
	@echo "    USE_CLIQUER       = $(USE_CLIQUER)"
	@echo "    CLIQUER_CFLAGS    = $(CLIQUER_CFLAGS)"
	@echo "    CLIQUER_LDFLAGS   = $(CLIQUER_LDFLAGS)"
	@echo "    CUDD_CFLAGS       = $(CUDD_CFLAGS)"
	@echo "    CUDD_LDFLAGS      = $(CUDD_LDFLAGS)"
	@echo "    USE_CUDD          = $(USE_CUDD)"
	@echo "    SQLITE_CFLAGS     = $(SQLITE_CFLAGS)"
	@echo "    SQLITE_LDFLAGS    = $(SQLITE_LDFLAGS)"
	@echo "    USE_SQLITE        = $(USE_SQLITE)"
	@echo ""
	@echo "    CPLEX_CFLAGS    = $(CPLEX_CFLAGS)"
	@echo "    CPLEX_LDFLAGS   = $(CPLEX_LDFLAGS)"
	@echo "    GUROBI_CFLAGS   = $(GUROBI_CFLAGS)"
	@echo "    GUROBI_LDFLAGS  = $(GUROBI_LDFLAGS)"
	@echo "    LPSOLVE_CFLAGS  = $(LPSOLVE_CFLAGS)"
	@echo "    LPSOLVE_LDFLAGS = $(LPSOLVE_LDFLAGS)"
	@echo "    LP_LDFLAGS      = $(LP_LDFLAGS)"
	@echo "    CPOPTIMIZER_CPPFLAGS = $(CPOPTIMIZER_CPPFLAGS)"
	@echo "    CPOPTIMIZER_LDFLAGS  = $(CPOPTIMIZER_LDFLAGS)"
	@echo
	@echo "Boruvka make variables: $(_BOR_MAKE_DEF)"

# These variables should not be passed to sub-makes
unexport CFLAGS
unexport CXXFLAGS
unexport LDFLAGS
